package modelos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Modulo.java
//  @ Date : 16/03/2012
//  @ Author : 
//
//




public class Modulo {
	private String codigoModulo = "ADMROL";
        private String codigo;
	private String nombre;
	private Boolean acceso;
	private Boolean adiccionar;
	private Boolean editar;
	private Boolean eliminar;
}
