package modelos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rol.java
//  @ Date : 16/03/2012
//  @ Author : 
//
//




public class Rol {
	private String nombre;
	private String descrip;
	private String codModulo;
	private String codigo;
        
        
}
