package modelos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rol.java
//  @ Date : 16/03/2012
//  @ Author : RicardoGS
//
//




public class Rol {
	private String nombre;
	private String descrip;
	private String codigoModulo = "ADMROL";
	private String codigo;

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescrip() {
        return descrip;
    }

    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodModulo() {
        return codigoModulo;
    }
        
        
}
